author:
        name: Microsoft

description: Text Classificaion using SQL Server + ML Services with R or Python
# names
solution_name: TextClassification
folder_name: TextClassification
db_name: TextClassification
ps1_name: TextClassificationSetup.ps1
pbix_name: TextClassification.pbix

cig_text: SQL Server VM on Azure
onp_text: SQL Server On-Premises 

# urls
code_url: "https://github.com/Microsoft/ml-server-text-classification"
website_url: "https://microsoft.github.io/ml-server-text-classification/"  
aka_url: "http://aka.ms/text-classification" 

