author:
        name: Microsoft

description: Text Classificaion using SQL Server 2017 + ML Services with R or Python
# names
solution_name: TextClassification
folder_name: TextClassification
db_name: Text
ps1_name: SetupVM.ps1
jupyter_name: Train Model.ipynb


# urls
code_url: "https://github.com/Microsoft/ml-server-text-classification"
website_url: "https://microsoft.github.io/ml-server-text-classification/"  
aka_url: "http://aka.ms/text-classification" 

